// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSCMJlN_1MpD-9-shNfj7IxlC1x2hLF_w',
    appId: '1:2369548471:web:f0535b1784bcb7d14e9d32',
    messagingSenderId: '2369548471',
    projectId: 'weather-app-cdc9a',
    authDomain: 'weather-app-cdc9a.firebaseapp.com',
    storageBucket: 'weather-app-cdc9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJ5KRCQc50-Tk7Kxbbmh0hL70LbngY70',
    appId: '1:2369548471:android:57d21432ae95b6174e9d32',
    messagingSenderId: '2369548471',
    projectId: 'weather-app-cdc9a',
    storageBucket: 'weather-app-cdc9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcu_LCXFQ9VA7Vm-YLf0r8ym0EqpoDlvw',
    appId: '1:2369548471:ios:9e1ecade169558304e9d32',
    messagingSenderId: '2369548471',
    projectId: 'weather-app-cdc9a',
    storageBucket: 'weather-app-cdc9a.firebasestorage.app',
    iosBundleId: 'com.eshem.weatherAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcu_LCXFQ9VA7Vm-YLf0r8ym0EqpoDlvw',
    appId: '1:2369548471:ios:9e1ecade169558304e9d32',
    messagingSenderId: '2369548471',
    projectId: 'weather-app-cdc9a',
    storageBucket: 'weather-app-cdc9a.firebasestorage.app',
    iosBundleId: 'com.eshem.weatherAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSCMJlN_1MpD-9-shNfj7IxlC1x2hLF_w',
    appId: '1:2369548471:web:f511eaa483024ac84e9d32',
    messagingSenderId: '2369548471',
    projectId: 'weather-app-cdc9a',
    authDomain: 'weather-app-cdc9a.firebaseapp.com',
    storageBucket: 'weather-app-cdc9a.firebasestorage.app',
  );
}
